### ISSUE TITLE
sqrt hangs on some values (as you knew)

### ISSUE THREAD

**Issue by knirch** [gibbsly/gm#15]
Noticed it breaks on 1.555;

1.5    -> 1.2247448
1.55   -> 1.2449899
1.555  -> FAIL
1.5555 -> 1.2471968

took a look to see if I understood the code, I did not, but I did notice that the position doesn't change. Threw some kludge on it, and now function gm:sqrt {x:1.555f} gladly produces 1.2469964

Sorry for not making a pull request or something polished, but I'm assuming this is probably not how you'd want it fixed.

```diff
-execute unless data storage gm._temp_:std {v1m2p:"-"} run return run function gm:zzz/sqrt_handling with storage gm._temp_:std
+
+# Only recurse if position actually changed, why? idk, all of this is O_O to me :D
+execute store result storage gm._temp_:std fff int 1 run data modify storage gm._temp_:std prev set from entity 91bb5-0-0-0-ffff Pos[1]
+execute unless data storage gm._temp_:std {fff:0} run execute unless data storage gm._temp_:std {v1m2p:"-"} run return run function gm:zzz/sqrt_handling with storage gm._temp_:std
```

**Comment by GlitchlessCode** [comment]
Hey there! Author of the sqrt code here.

Thanks for reporting this issue! I'll take a look at it when I get a moment, and I'll try and have a PR in ASAP. I was worried that this could become an issue, so I'll try an find a more permanent solution. I will look at your proposed solution as well, though I will need to run it through a slew of tests to see what other effects it might (unintentionally) have.

In case you're curious what's actually going on, and why it hangs/fails:
It uses a recursive algorithm where the result of the previous recursion is always passed in to the next call. There are two separate values, one that starts at 1, and one that starts at the value you want to get the square root of. They both slowly approach the value of the sqrt, getting closer and closer. To detect when it's "good enough" to end the recursion and use that final result as the return value, I detect when the higher value minus the lower value minus some threshold value (in this case, 0.000000001, found in `.../zzz/sqrt/positive_subtract.mcfunction`, line 9) is negative. If it is positive, then it recurses again, if it's negative, then we are within that threshold, and so we can stop recursing, and return that value.
However in some cases, usually due to floating point rounding, it never gets quite close enough for the threshold to be met, thus it hangs.

**Comment by GlitchlessCode** [comment]
Hope that helps!
